"""Overseer API – Report scheduling, generation, delivery, and history."""
import os
import shutil
from datetime import date, datetime, timezone
from pathlib import Path
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, Response, UploadFile, File
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field
from sqlalchemy import select, func, desc
from sqlalchemy.ext.asyncio import AsyncSession

from api.app.core.database import get_db
from api.app.core.auth import get_current_user, require_role, tenant_scope, apply_tenant_filter
from api.app.models.models import ReportSchedule, ReportDelivery
from api.app.routers.audit import write_audit

LOGO_UPLOAD_DIR = Path(os.getenv("REPORT_LOGO_DIR", "/opt/overseer/reports/logos"))
ALLOWED_LOGO_TYPES = {"image/png", "image/jpeg", "image/svg+xml"}
MAX_LOGO_SIZE = 2 * 1024 * 1024  # 2 MB

router = APIRouter()


# ── Pydantic Schemas ──────────────────────────────────────────────────────────

class RecipientsSchema(BaseModel):
    to: list[str] = []
    cc: list[str] = []
    bcc: list[str] = []


class ScopeSchema(BaseModel):
    host_ids: list[str] | None = None
    tags: list[str] | None = None


class BrandingSchema(BaseModel):
    logo_path: str | None = None
    company_name: str = "Overseer"
    primary_color: str = "#3b82f6"
    footer_text: str = "Generated by Overseer"


class ScheduleCreate(BaseModel):
    tenant_id: str
    name: str = Field(..., max_length=255)
    report_type: str = Field(..., pattern="^(executive|technical|sla)$")
    cron_expression: str = Field(..., max_length=100)
    recipients: RecipientsSchema
    scope: ScopeSchema | None = None
    branding: BrandingSchema = Field(default_factory=BrandingSchema)
    cover_text: str | None = None
    timezone: str = "Europe/Rome"
    enabled: bool = True


class ScheduleUpdate(BaseModel):
    name: str | None = None
    report_type: str | None = None
    cron_expression: str | None = None
    recipients: RecipientsSchema | None = None
    scope: ScopeSchema | None = None
    branding: BrandingSchema | None = None
    cover_text: str | None = None
    timezone: str | None = None
    enabled: bool | None = None


class ScheduleOut(BaseModel):
    id: str
    tenant_id: str
    name: str
    report_type: str
    cron_expression: str
    recipients: dict
    scope: dict | None
    branding: dict
    cover_text: str | None
    timezone: str
    enabled: bool
    last_run_at: str | None
    next_run_at: str | None
    created_by: str | None
    created_at: str

    model_config = {"from_attributes": True}


class DeliveryOut(BaseModel):
    id: str
    schedule_id: str | None
    tenant_id: str
    report_type: str
    report_period_start: str
    report_period_end: str
    pdf_path: str | None
    pdf_size_bytes: int | None
    recipients: dict | None
    status: str
    error_message: str | None
    generated_at: str | None
    sent_at: str | None
    created_by: str | None
    created_at: str
    schedule_name: str | None = None

    model_config = {"from_attributes": True}


class GenerateNowRequest(BaseModel):
    tenant_id: str
    report_type: str = Field(..., pattern="^(executive|technical|sla)$")
    period_start: str  # YYYY-MM-DD
    period_end: str  # YYYY-MM-DD
    recipients: RecipientsSchema | None = None
    branding: BrandingSchema = Field(default_factory=BrandingSchema)
    cover_text: str | None = None
    scope: ScopeSchema | None = None


# ── Helper ────────────────────────────────────────────────────────────────────

def _check_tenant_access(tenant_id: UUID, scope):
    if scope is not None and tenant_id not in scope:
        raise HTTPException(status_code=403, detail="Access denied to this tenant")


def _schedule_to_out(s: ReportSchedule) -> dict:
    return {
        "id": str(s.id),
        "tenant_id": str(s.tenant_id),
        "name": s.name,
        "report_type": s.report_type,
        "cron_expression": s.cron_expression,
        "recipients": s.recipients or {},
        "scope": s.scope,
        "branding": s.branding or {},
        "cover_text": s.cover_text,
        "timezone": s.timezone,
        "enabled": s.enabled,
        "last_run_at": s.last_run_at.isoformat() if s.last_run_at else None,
        "next_run_at": s.next_run_at.isoformat() if s.next_run_at else None,
        "created_by": str(s.created_by) if s.created_by else None,
        "created_at": s.created_at.isoformat() if s.created_at else None,
    }


def _delivery_to_out(d: ReportDelivery, schedule_name: str | None = None) -> dict:
    return {
        "id": str(d.id),
        "schedule_id": str(d.schedule_id) if d.schedule_id else None,
        "tenant_id": str(d.tenant_id),
        "report_type": d.report_type,
        "report_period_start": d.report_period_start.isoformat() if d.report_period_start else None,
        "report_period_end": d.report_period_end.isoformat() if d.report_period_end else None,
        "pdf_path": d.pdf_path,
        "pdf_size_bytes": d.pdf_size_bytes,
        "recipients": d.recipients,
        "status": d.status,
        "error_message": d.error_message,
        "generated_at": d.generated_at.isoformat() if d.generated_at else None,
        "sent_at": d.sent_at.isoformat() if d.sent_at else None,
        "created_by": str(d.created_by) if d.created_by else None,
        "created_at": d.created_at.isoformat() if d.created_at else None,
        "schedule_name": schedule_name,
    }


# ── Schedules CRUD ────────────────────────────────────────────────────────────

@router.get("/schedules")
async def list_schedules(
    tenant_id: UUID | None = None,
    db: AsyncSession = Depends(get_db),
    user: dict = Depends(get_current_user),
    scope=Depends(tenant_scope),
):
    q = select(ReportSchedule).order_by(ReportSchedule.created_at.desc())
    q = apply_tenant_filter(q, ReportSchedule.tenant_id, scope, tenant_id)
    result = await db.execute(q)
    schedules = result.scalars().all()
    return [_schedule_to_out(s) for s in schedules]


@router.get("/schedules/{schedule_id}")
async def get_schedule(
    schedule_id: UUID,
    db: AsyncSession = Depends(get_db),
    user: dict = Depends(get_current_user),
    scope=Depends(tenant_scope),
):
    s = await db.get(ReportSchedule, schedule_id)
    if not s:
        raise HTTPException(status_code=404, detail="Schedule not found")
    _check_tenant_access(s.tenant_id, scope)
    return _schedule_to_out(s)


@router.post("/schedules", status_code=201)
async def create_schedule(
    body: ScheduleCreate,
    db: AsyncSession = Depends(get_db),
    user: dict = Depends(require_role("super_admin", "tenant_admin")),
    scope=Depends(tenant_scope),
):
    tenant_id = UUID(body.tenant_id)
    _check_tenant_access(tenant_id, scope)

    # Validate cron expression
    try:
        from apscheduler.triggers.cron import CronTrigger
        CronTrigger.from_crontab(body.cron_expression, timezone=body.timezone)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Invalid cron expression: {e}")

    sched = ReportSchedule(
        tenant_id=tenant_id,
        name=body.name,
        report_type=body.report_type,
        cron_expression=body.cron_expression,
        recipients=body.recipients.model_dump(),
        scope=body.scope.model_dump() if body.scope else None,
        branding=body.branding.model_dump(),
        cover_text=body.cover_text,
        timezone=body.timezone,
        enabled=body.enabled,
        created_by=UUID(user["sub"]) if user.get("sub") else None,
    )

    # Compute next_run_at
    from reports.scheduler import _next_run, register_schedule
    sched.next_run_at = _next_run(body.cron_expression, body.timezone)

    db.add(sched)
    await write_audit(db, user=user, action="report_schedule_create",
                      target_type="report_schedule", target_id=sched.id, tenant_id=tenant_id,
                      detail={"name": body.name, "report_type": body.report_type})
    await db.commit()

    # Register with APScheduler
    if sched.enabled:
        register_schedule(sched)

    return _schedule_to_out(sched)


@router.patch("/schedules/{schedule_id}")
async def update_schedule(
    schedule_id: UUID,
    body: ScheduleUpdate,
    db: AsyncSession = Depends(get_db),
    user: dict = Depends(require_role("super_admin", "tenant_admin")),
    scope=Depends(tenant_scope),
):
    sched = await db.get(ReportSchedule, schedule_id)
    if not sched:
        raise HTTPException(status_code=404, detail="Schedule not found")
    _check_tenant_access(sched.tenant_id, scope)

    changes = body.model_dump(exclude_unset=True)

    if "cron_expression" in changes or "timezone" in changes:
        cron = changes.get("cron_expression", sched.cron_expression)
        tz = changes.get("timezone", sched.timezone)
        try:
            from apscheduler.triggers.cron import CronTrigger
            CronTrigger.from_crontab(cron, timezone=tz)
        except Exception as e:
            raise HTTPException(status_code=400, detail=f"Invalid cron expression: {e}")

    if "recipients" in changes:
        changes["recipients"] = body.recipients.model_dump()
    if "scope" in changes:
        changes["scope"] = body.scope.model_dump() if body.scope else None
    if "branding" in changes:
        changes["branding"] = body.branding.model_dump()

    for key, val in changes.items():
        setattr(sched, key, val)
    sched.updated_at = datetime.now(timezone.utc)

    # Recompute next_run
    from reports.scheduler import _next_run, register_schedule, unregister_schedule
    sched.next_run_at = _next_run(sched.cron_expression, sched.timezone)

    await write_audit(db, user=user, action="report_schedule_update",
                      target_type="report_schedule", target_id=schedule_id, tenant_id=sched.tenant_id,
                      detail=changes)
    await db.commit()

    # Update APScheduler
    if sched.enabled:
        register_schedule(sched)
    else:
        unregister_schedule(schedule_id)

    return _schedule_to_out(sched)


@router.delete("/schedules/{schedule_id}", status_code=204)
async def delete_schedule(
    schedule_id: UUID,
    db: AsyncSession = Depends(get_db),
    user: dict = Depends(require_role("super_admin", "tenant_admin")),
    scope=Depends(tenant_scope),
):
    sched = await db.get(ReportSchedule, schedule_id)
    if not sched:
        raise HTTPException(status_code=404, detail="Schedule not found")
    _check_tenant_access(sched.tenant_id, scope)

    from reports.scheduler import unregister_schedule
    unregister_schedule(schedule_id)

    await write_audit(db, user=user, action="report_schedule_delete",
                      target_type="report_schedule", target_id=schedule_id, tenant_id=sched.tenant_id,
                      detail={"name": sched.name})
    await db.delete(sched)
    await db.commit()
    return Response(status_code=204)


# ── Generate Now (on-demand) ──────────────────────────────────────────────────

@router.post("/generate")
async def generate_report_now(
    body: GenerateNowRequest,
    db: AsyncSession = Depends(get_db),
    user: dict = Depends(require_role("super_admin", "tenant_admin")),
    scope=Depends(tenant_scope),
):
    tenant_id = UUID(body.tenant_id)
    _check_tenant_access(tenant_id, scope)

    try:
        period_start = date.fromisoformat(body.period_start)
        period_end = date.fromisoformat(body.period_end)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid date format, use YYYY-MM-DD")

    if period_start > period_end:
        raise HTTPException(status_code=400, detail="period_start must be before period_end")

    from reports.scheduler import generate_on_demand
    delivery_id = await generate_on_demand(
        db,
        tenant_id=tenant_id,
        report_type=body.report_type,
        period_start=period_start,
        period_end=period_end,
        recipients=body.recipients.model_dump() if body.recipients else None,
        branding_data=body.branding.model_dump(),
        cover_text=body.cover_text,
        scope=body.scope.model_dump() if body.scope else None,
        created_by=UUID(user["sub"]) if user.get("sub") else None,
    )

    delivery = await db.get(ReportDelivery, delivery_id)
    return _delivery_to_out(delivery)


# ── Preview (HTML only, no PDF, no email) ─────────────────────────────────────

@router.post("/preview")
async def preview_report(
    body: GenerateNowRequest,
    db: AsyncSession = Depends(get_db),
    user: dict = Depends(require_role("super_admin", "tenant_admin")),
    scope=Depends(tenant_scope),
):
    tenant_id = UUID(body.tenant_id)
    _check_tenant_access(tenant_id, scope)

    try:
        period_start = date.fromisoformat(body.period_start)
        period_end = date.fromisoformat(body.period_end)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid date format")

    from reports.engine import ReportEngine, ReportRequest, Branding

    branding_data = body.branding.model_dump()
    branding = Branding(
        logo_path=branding_data.get("logo_path"),
        company_name=branding_data.get("company_name", "Overseer"),
        primary_color=branding_data.get("primary_color", "#3b82f6"),
        footer_text=branding_data.get("footer_text", "Generated by Overseer"),
    )

    scope_data = body.scope.model_dump() if body.scope else {}
    scope_host_ids = [UUID(h) for h in scope_data["host_ids"]] if scope_data.get("host_ids") else None
    scope_tags = scope_data.get("tags")

    request = ReportRequest(
        tenant_id=tenant_id,
        report_type=body.report_type,
        period_start=period_start,
        period_end=period_end,
        branding=branding,
        cover_text=body.cover_text,
        scope_host_ids=scope_host_ids,
        scope_tags=scope_tags,
    )

    engine = ReportEngine()
    html = await engine.generate_html_preview(db, request)
    return Response(content=html, media_type="text/html")


# ── Logo Upload ───────────────────────────────────────────────────────────────

@router.post("/upload-logo")
async def upload_logo(
    file: UploadFile = File(...),
    user: dict = Depends(require_role("super_admin", "tenant_admin")),
):
    if file.content_type not in ALLOWED_LOGO_TYPES:
        raise HTTPException(status_code=400, detail="Only PNG, JPG, and SVG are allowed")

    data = await file.read()
    if len(data) > MAX_LOGO_SIZE:
        raise HTTPException(status_code=400, detail="File too large (max 2 MB)")

    LOGO_UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

    ext = file.filename.rsplit(".", 1)[-1] if "." in (file.filename or "") else "png"
    import uuid as _uuid
    filename = f"{_uuid.uuid4().hex}.{ext}"
    dest = LOGO_UPLOAD_DIR / filename
    dest.write_bytes(data)

    return {"logo_path": str(dest)}


# ── Delivery History ──────────────────────────────────────────────────────────

@router.get("/history")
async def list_deliveries(
    tenant_id: UUID | None = None,
    schedule_id: UUID | None = None,
    status: str | None = None,
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    db: AsyncSession = Depends(get_db),
    user: dict = Depends(get_current_user),
    scope=Depends(tenant_scope),
):
    q = select(ReportDelivery).order_by(ReportDelivery.created_at.desc())
    q = apply_tenant_filter(q, ReportDelivery.tenant_id, scope, tenant_id)

    if schedule_id:
        q = q.where(ReportDelivery.schedule_id == schedule_id)
    if status:
        q = q.where(ReportDelivery.status == status)

    # Count
    count_q = select(func.count()).select_from(q.subquery())
    total = (await db.execute(count_q)).scalar() or 0

    q = q.limit(limit).offset(offset)
    result = await db.execute(q)
    deliveries = result.scalars().all()

    # Fetch schedule names
    sched_ids = {d.schedule_id for d in deliveries if d.schedule_id}
    sched_names: dict[UUID, str] = {}
    if sched_ids:
        sched_result = await db.execute(
            select(ReportSchedule.id, ReportSchedule.name).where(ReportSchedule.id.in_(sched_ids))
        )
        sched_names = {row.id: row.name for row in sched_result}

    items = [
        _delivery_to_out(d, sched_names.get(d.schedule_id))
        for d in deliveries
    ]

    return Response(
        content=__import__("json").dumps(items),
        media_type="application/json",
        headers={"X-Total-Count": str(total)},
    )


# ── Download PDF ──────────────────────────────────────────────────────────────

@router.get("/download/{delivery_id}")
async def download_report(
    delivery_id: UUID,
    db: AsyncSession = Depends(get_db),
    user: dict = Depends(get_current_user),
    scope=Depends(tenant_scope),
):
    d = await db.get(ReportDelivery, delivery_id)
    if not d:
        raise HTTPException(status_code=404, detail="Delivery not found")
    _check_tenant_access(d.tenant_id, scope)

    if not d.pdf_path:
        raise HTTPException(status_code=404, detail="PDF not available (expired or not generated)")

    pdf_path = Path(d.pdf_path)
    if not pdf_path.exists():
        raise HTTPException(status_code=404, detail="PDF file not found on disk")

    return FileResponse(
        path=str(pdf_path),
        media_type="application/pdf",
        filename=pdf_path.name,
    )


# ── Resend / Retry ────────────────────────────────────────────────────────────

@router.post("/resend/{delivery_id}")
async def resend_report(
    delivery_id: UUID,
    db: AsyncSession = Depends(get_db),
    user: dict = Depends(require_role("super_admin", "tenant_admin")),
    scope=Depends(tenant_scope),
):
    d = await db.get(ReportDelivery, delivery_id)
    if not d:
        raise HTTPException(status_code=404, detail="Delivery not found")
    _check_tenant_access(d.tenant_id, scope)

    if not d.pdf_path or not Path(d.pdf_path).exists():
        raise HTTPException(status_code=400, detail="PDF not available — use retry to regenerate")

    recipients = d.recipients or {}
    to_list = recipients.get("to", [])
    if not to_list:
        raise HTTPException(status_code=400, detail="No recipients")

    from shared.email import send_email_with_attachment

    pdf_data = Path(d.pdf_path).read_bytes()
    pdf_filename = Path(d.pdf_path).name
    subject = f"Overseer — Report (resent) {d.report_period_start} – {d.report_period_end}"
    body_plain = f"Re-sending your {d.report_type} report for {d.report_period_start} to {d.report_period_end}."

    try:
        await send_email_with_attachment(
            to=to_list,
            subject=subject,
            body_plain=body_plain,
            attachments=[(pdf_filename, pdf_data)],
            cc=recipients.get("cc", []),
            bcc=recipients.get("bcc", []),
        )
        d.status = "sent"
        d.sent_at = datetime.now(timezone.utc)
        d.error_message = None
    except Exception as e:
        d.error_message = f"Resend failed: {e}"

    await db.commit()
    return _delivery_to_out(d)


@router.post("/retry/{delivery_id}")
async def retry_report(
    delivery_id: UUID,
    db: AsyncSession = Depends(get_db),
    user: dict = Depends(require_role("super_admin", "tenant_admin")),
    scope=Depends(tenant_scope),
):
    """Regenerate and resend a failed report."""
    d = await db.get(ReportDelivery, delivery_id)
    if not d:
        raise HTTPException(status_code=404, detail="Delivery not found")
    _check_tenant_access(d.tenant_id, scope)

    from reports.scheduler import generate_on_demand
    new_delivery_id = await generate_on_demand(
        db,
        tenant_id=d.tenant_id,
        report_type=d.report_type,
        period_start=d.report_period_start if isinstance(d.report_period_start, date) else date.fromisoformat(str(d.report_period_start)),
        period_end=d.report_period_end if isinstance(d.report_period_end, date) else date.fromisoformat(str(d.report_period_end)),
        recipients=d.recipients,
        created_by=UUID(user["sub"]) if user.get("sub") else None,
    )

    new_d = await db.get(ReportDelivery, new_delivery_id)
    return _delivery_to_out(new_d)
