"""Report Engine — orchestrates data collection, chart generation, HTML rendering, PDF output."""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from pathlib import Path
from uuid import UUID

from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML
from sqlalchemy.ext.asyncio import AsyncSession

from reports.data_collector import collect_report_data, ReportData
from reports.chart_generator import (
    generate_uptime_bar_chart,
    generate_performance_timeseries,
    generate_health_gauge,
    generate_incident_timeline,
)

TEMPLATE_DIR = Path(__file__).parent / "templates"
PDF_OUTPUT_DIR = Path(os.getenv("REPORT_PDF_DIR", "/opt/overseer/reports"))


@dataclass
class Branding:
    logo_path: str | None = None
    company_name: str = "Overseer"
    primary_color: str = "#3b82f6"
    footer_text: str = "Generated by Overseer"


@dataclass
class ReportRequest:
    tenant_id: UUID
    report_type: str  # 'executive', 'technical'
    period_start: date
    period_end: date
    branding: Branding = field(default_factory=Branding)
    cover_text: str | None = None
    scope_host_ids: list[UUID] | None = None
    scope_tags: list[str] | None = None


class ReportEngine:
    """Orchestrates the full report generation pipeline."""

    def __init__(self) -> None:
        self.jinja_env = Environment(
            loader=FileSystemLoader(str(TEMPLATE_DIR)),
            autoescape=False,
        )

    async def generate(self, db: AsyncSession, request: ReportRequest) -> Path:
        """Generate a PDF report and return the file path.

        Pipeline:
        1. Collect report data from DB (aggregate views)
        2. Generate SVG charts (Plotly/Kaleido)
        3. Render HTML (Jinja2)
        4. Convert to PDF (WeasyPrint)
        """
        # 1. Collect data
        data = await collect_report_data(
            db=db,
            tenant_id=request.tenant_id,
            period_start=request.period_start,
            period_end=request.period_end,
            scope_host_ids=request.scope_host_ids,
            scope_tags=request.scope_tags,
        )

        # Check for limited data
        limited_data = any(s.total_checks < 10 for s in data.services_sla)

        # 2. Generate charts
        charts = await self._generate_charts(db, data, request)

        # 3. Render HTML
        template_name = f"{request.report_type}.html"
        template = self.jinja_env.get_template(template_name)

        report_title = self._report_title(request)
        html_content = template.render(
            data=data,
            charts=charts,
            branding=request.branding,
            report_title=report_title,
            cover_text=request.cover_text,
            limited_data=limited_data,
        )

        # 4. Generate PDF
        pdf_path = self._pdf_path(request, data)
        pdf_path.parent.mkdir(parents=True, exist_ok=True)

        html_doc = HTML(
            string=html_content,
            base_url=str(TEMPLATE_DIR),
        )
        html_doc.write_pdf(str(pdf_path))

        return pdf_path

    async def generate_html_preview(self, db: AsyncSession, request: ReportRequest) -> str:
        """Generate HTML preview (no PDF) for browser display."""
        data = await collect_report_data(
            db=db,
            tenant_id=request.tenant_id,
            period_start=request.period_start,
            period_end=request.period_end,
            scope_host_ids=request.scope_host_ids,
            scope_tags=request.scope_tags,
        )
        limited_data = any(s.total_checks < 10 for s in data.services_sla)
        charts = await self._generate_charts(db, data, request)

        template = self.jinja_env.get_template(f"{request.report_type}.html")
        return template.render(
            data=data,
            charts=charts,
            branding=request.branding,
            report_title=self._report_title(request),
            cover_text=request.cover_text,
            limited_data=limited_data,
        )

    async def _generate_charts(
        self, db: AsyncSession, data: ReportData, request: ReportRequest
    ) -> dict[str, str]:
        """Generate all charts as SVG strings."""
        charts: dict[str, str] = {}

        # Health gauge
        charts["health_gauge"] = generate_health_gauge(data.health_score)

        # Uptime bar chart
        if data.services_sla:
            sla_data = [
                {
                    "name": s.service_name,
                    "sla_pct": s.sla_pct,
                    "target": s.sla_target,
                }
                for s in sorted(data.services_sla, key=lambda x: x.sla_pct)[:20]
            ]
            charts["uptime_bar"] = generate_uptime_bar_chart(
                sla_data, title="Service Availability"
            )

        # Incident timeline
        if data.incidents:
            inc_data = [
                {
                    "service_name": i.service_name,
                    "started_at": i.started_at,
                    "duration_minutes": i.duration_minutes,
                    "severity": i.severity,
                }
                for i in data.incidents[:20]
            ]
            timeline = generate_incident_timeline(inc_data)
            if timeline:
                charts["incident_timeline"] = timeline

        # Performance timeseries (only for technical reports)
        if request.report_type == "technical" and data.performance:
            ts_start = datetime(
                request.period_start.year, request.period_start.month,
                request.period_start.day, tzinfo=timezone.utc,
            )
            ts_end = datetime(
                request.period_end.year, request.period_end.month,
                request.period_end.day, 23, 59, 59, tzinfo=timezone.utc,
            )

            # Group by check_type for separate charts
            by_type: dict[str, list] = {}
            for p in data.performance:
                by_type.setdefault(p.check_type, []).append(p)

            for check_type, metrics in by_type.items():
                svc_ids = [UUID(m.service_id) for m in metrics[:8]]
                svc_names = {m.service_id: f"{m.host_name}: {m.service_name}" for m in metrics[:8]}
                unit = metrics[0].unit if metrics else ""
                chart_svg = await generate_performance_timeseries(
                    db, svc_ids, ts_start, ts_end, svc_names,
                    title=check_type.replace("agent_", "").replace("_", " ").title(),
                    value_label=unit or "Value",
                )
                charts[f"perf_{check_type}"] = chart_svg

        return charts

    @staticmethod
    def _report_title(request: ReportRequest) -> str:
        type_names = {
            "executive": "Executive Summary",
            "technical": "Technischer Report",
            "sla": "SLA Report",
        }
        return type_names.get(request.report_type, "Report")

    @staticmethod
    def _pdf_path(request: ReportRequest, data: ReportData) -> Path:
        """Generate a unique PDF file path."""
        ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        filename = (
            f"{data.tenant_name.replace(' ', '_')}_{request.report_type}"
            f"_{request.period_start.isoformat()}_{request.period_end.isoformat()}"
            f"_{ts}.pdf"
        )
        return PDF_OUTPUT_DIR / str(request.tenant_id) / filename
