"""Report Scheduler — APScheduler integration for periodic report generation + delivery."""
from __future__ import annotations

import asyncio
import logging
import os
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from uuid import UUID

from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.cron import CronTrigger
from sqlalchemy import select, text, update
from sqlalchemy.ext.asyncio import AsyncSession

from api.app.core.database import AsyncSessionLocal

logger = logging.getLogger("overseer.reports")

PDF_OUTPUT_DIR = Path(os.getenv("REPORT_PDF_DIR", "/opt/overseer/reports"))
LOGO_UPLOAD_DIR = Path(os.getenv("REPORT_LOGO_DIR", "/opt/overseer/reports/logos"))

scheduler = AsyncIOScheduler()
_engine = None


def _get_engine():
    global _engine
    if _engine is None:
        from reports.engine import ReportEngine
        _engine = ReportEngine()
    return _engine

# Retry config: 3 attempts with backoff
RETRY_DELAYS = [5, 30, 60]


def _compute_period(cron_expr: str, tz: str) -> tuple[date, date]:
    """Compute the report period (start, end) based on cron frequency.

    Heuristic: if cron runs on day 1 → monthly, if weekday-based → weekly, else monthly.
    The period ends yesterday, starts based on frequency.
    """
    yesterday = date.today() - timedelta(days=1)

    parts = cron_expr.split()
    day_of_month = parts[2] if len(parts) >= 3 else "*"
    day_of_week = parts[4] if len(parts) >= 5 else "*"

    if day_of_week != "*" and day_of_month == "*":
        # Weekly: last 7 days
        return yesterday - timedelta(days=6), yesterday

    if day_of_month == "1":
        # Monthly: previous full month
        first_of_this_month = yesterday.replace(day=1)
        last_of_prev_month = first_of_this_month - timedelta(days=1)
        first_of_prev_month = last_of_prev_month.replace(day=1)
        return first_of_prev_month, last_of_prev_month

    # Default: last 30 days
    return yesterday - timedelta(days=29), yesterday


async def generate_and_send_report(schedule_id: str) -> None:
    """Generate a report for a schedule and send it via email."""
    from api.app.models.models import ReportSchedule, ReportDelivery
    from shared.email import send_email_with_attachment

    from reports.engine import ReportRequest, Branding

    async with AsyncSessionLocal() as db:
        sched = await db.get(ReportSchedule, UUID(schedule_id))
        if not sched or not sched.enabled:
            return

        period_start, period_end = _compute_period(sched.cron_expression, sched.timezone)

        # Create delivery record
        delivery = ReportDelivery(
            schedule_id=sched.id,
            tenant_id=sched.tenant_id,
            report_type=sched.report_type,
            report_period_start=period_start,
            report_period_end=period_end,
            recipients=sched.recipients,
            status="generating",
        )
        db.add(delivery)
        await db.flush()
        delivery_id = delivery.id

        try:
            branding_data = sched.branding or {}
            branding = Branding(
                logo_path=branding_data.get("logo_path"),
                company_name=branding_data.get("company_name", "Overseer"),
                primary_color=branding_data.get("primary_color", "#3b82f6"),
                footer_text=branding_data.get("footer_text", "Generated by Overseer"),
            )

            scope_data = sched.scope or {}
            scope_host_ids = [UUID(h) for h in scope_data["host_ids"]] if scope_data.get("host_ids") else None
            scope_tags = scope_data.get("tags")

            request = ReportRequest(
                tenant_id=sched.tenant_id,
                report_type=sched.report_type,
                period_start=period_start,
                period_end=period_end,
                branding=branding,
                cover_text=sched.cover_text,
                scope_host_ids=scope_host_ids,
                scope_tags=scope_tags,
            )

            # Generate PDF
            pdf_path = await _get_engine().generate(db, request)
            pdf_size = pdf_path.stat().st_size

            delivery.pdf_path = str(pdf_path)
            delivery.pdf_size_bytes = pdf_size
            delivery.generated_at = datetime.now(timezone.utc)
            delivery.status = "sending"
            await db.flush()

            # Send email with retry
            recipients = sched.recipients or {}
            to_list = recipients.get("to", [])
            cc_list = recipients.get("cc", [])
            bcc_list = recipients.get("bcc", [])

            if to_list:
                pdf_data = pdf_path.read_bytes()
                pdf_filename = pdf_path.name

                company = branding.company_name
                subject = f"{company} — {sched.name} ({period_start.isoformat()} – {period_end.isoformat()})"
                body_plain = (
                    f"Your {sched.report_type} report for {period_start} to {period_end} is attached.\n\n"
                    f"Generated by {company}."
                )
                body_html = _render_report_email_html(
                    company_name=company,
                    report_name=sched.name,
                    period_start=period_start,
                    period_end=period_end,
                    primary_color=branding.primary_color,
                )

                last_error = None
                for attempt, delay in enumerate(RETRY_DELAYS):
                    try:
                        await send_email_with_attachment(
                            to=to_list,
                            subject=subject,
                            body_plain=body_plain,
                            body_html=body_html,
                            attachments=[(pdf_filename, pdf_data)],
                            cc=cc_list,
                            bcc=bcc_list,
                        )
                        last_error = None
                        break
                    except Exception as e:
                        last_error = str(e)
                        logger.warning("[ReportDelivery] Attempt %d failed: %s", attempt + 1, e)
                        if attempt < len(RETRY_DELAYS) - 1:
                            await asyncio.sleep(delay)

                if last_error:
                    delivery.status = "failed"
                    delivery.error_message = last_error
                else:
                    delivery.status = "sent"
                    delivery.sent_at = datetime.now(timezone.utc)
            else:
                # No recipients — just mark as generated
                delivery.status = "sent"
                delivery.sent_at = datetime.now(timezone.utc)

            # Update schedule
            sched.last_run_at = datetime.now(timezone.utc)
            sched.next_run_at = _next_run(sched.cron_expression, sched.timezone)

        except Exception as e:
            logger.error("[ReportDelivery] Generation failed for schedule %s: %s", schedule_id, e)
            delivery.status = "failed"
            delivery.error_message = str(e)

        await db.commit()
        logger.info("[ReportDelivery] Schedule %s → delivery %s: %s", sched.name, delivery_id, delivery.status)


async def generate_on_demand(
    db: AsyncSession,
    *,
    tenant_id: UUID,
    report_type: str,
    period_start: date,
    period_end: date,
    recipients: dict | None = None,
    branding_data: dict | None = None,
    cover_text: str | None = None,
    scope: dict | None = None,
    created_by: UUID | None = None,
) -> UUID:
    """Generate an on-demand report (no schedule). Returns the delivery ID."""
    from api.app.models.models import ReportDelivery
    from reports.engine import ReportRequest, Branding

    branding_data = branding_data or {}
    branding = Branding(
        logo_path=branding_data.get("logo_path"),
        company_name=branding_data.get("company_name", "Overseer"),
        primary_color=branding_data.get("primary_color", "#3b82f6"),
        footer_text=branding_data.get("footer_text", "Generated by Overseer"),
    )

    scope = scope or {}
    scope_host_ids = [UUID(h) for h in scope["host_ids"]] if scope.get("host_ids") else None
    scope_tags = scope.get("tags")

    delivery = ReportDelivery(
        tenant_id=tenant_id,
        report_type=report_type,
        report_period_start=period_start,
        report_period_end=period_end,
        recipients=recipients,
        status="generating",
        created_by=created_by,
    )
    db.add(delivery)
    await db.flush()

    request = ReportRequest(
        tenant_id=tenant_id,
        report_type=report_type,
        period_start=period_start,
        period_end=period_end,
        branding=branding,
        cover_text=cover_text,
        scope_host_ids=scope_host_ids,
        scope_tags=scope_tags,
    )

    try:
        pdf_path = await _engine.generate(db, request)
        delivery.pdf_path = str(pdf_path)
        delivery.pdf_size_bytes = pdf_path.stat().st_size
        delivery.generated_at = datetime.now(timezone.utc)

        # Send if recipients provided
        if recipients and recipients.get("to"):
            from shared.email import send_email_with_attachment

            pdf_data = pdf_path.read_bytes()
            company = branding.company_name
            subject = f"{company} — Report ({period_start.isoformat()} – {period_end.isoformat()})"
            body_plain = f"Your {report_type} report for {period_start} to {period_end} is attached."
            body_html = _render_report_email_html(
                company_name=company,
                report_name=f"{report_type.title()} Report",
                period_start=period_start,
                period_end=period_end,
                primary_color=branding.primary_color,
            )

            try:
                await send_email_with_attachment(
                    to=recipients["to"],
                    subject=subject,
                    body_plain=body_plain,
                    body_html=body_html,
                    attachments=[(pdf_path.name, pdf_data)],
                    cc=recipients.get("cc", []),
                    bcc=recipients.get("bcc", []),
                )
                delivery.status = "sent"
                delivery.sent_at = datetime.now(timezone.utc)
            except Exception as e:
                delivery.status = "failed"
                delivery.error_message = f"Email failed: {e}"
        else:
            delivery.status = "sent"
            delivery.sent_at = datetime.now(timezone.utc)

    except Exception as e:
        delivery.status = "failed"
        delivery.error_message = str(e)
        logger.error("[ReportOnDemand] Failed: %s", e)

    await db.commit()
    return delivery.id


def _next_run(cron_expression: str, tz: str) -> datetime | None:
    """Compute next fire time from cron expression."""
    try:
        from zoneinfo import ZoneInfo
        trigger = CronTrigger.from_crontab(cron_expression, timezone=tz)
        return trigger.get_next_fire_time(None, datetime.now(ZoneInfo(tz)))
    except Exception:
        return None


async def load_schedules() -> None:
    """Load all active schedules from DB and register with APScheduler."""
    from api.app.models.models import ReportSchedule

    async with AsyncSessionLocal() as db:
        result = await db.execute(
            select(ReportSchedule).where(ReportSchedule.enabled == True)
        )
        schedules = result.scalars().all()

        for sched in schedules:
            _register_job(sched)
            logger.info("[ReportScheduler] Loaded schedule: %s (%s)", sched.name, sched.cron_expression)

    logger.info("[ReportScheduler] Loaded %d active schedule(s)", len(schedules))


def _register_job(sched) -> None:
    """Register a single schedule as an APScheduler job."""
    job_id = f"report_{sched.id}"
    try:
        scheduler.add_job(
            generate_and_send_report,
            trigger=CronTrigger.from_crontab(sched.cron_expression, timezone=sched.timezone or "Europe/Rome"),
            id=job_id,
            args=[str(sched.id)],
            replace_existing=True,
        )
    except Exception as e:
        logger.error("[ReportScheduler] Failed to register job %s: %s", sched.name, e)


def register_schedule(sched) -> None:
    """Register or update a schedule job (called when schedule is created/updated)."""
    _register_job(sched)


def unregister_schedule(schedule_id: UUID) -> None:
    """Remove a schedule job (called when schedule is disabled/deleted)."""
    job_id = f"report_{schedule_id}"
    try:
        scheduler.remove_job(job_id)
    except Exception:
        pass  # Job might not exist


async def start_scheduler() -> None:
    """Start the APScheduler and load existing schedules."""
    await load_schedules()
    scheduler.start()
    logger.info("[ReportScheduler] Started")


async def cleanup_old_pdfs() -> None:
    """Delete PDFs older than 90 days. Runs once daily."""
    await asyncio.sleep(3600)  # 1h initial delay
    while True:
        try:
            cutoff = datetime.now(timezone.utc) - timedelta(days=90)
            async with AsyncSessionLocal() as db:
                result = await db.execute(text("""
                    SELECT id, pdf_path FROM report_deliveries
                    WHERE pdf_path IS NOT NULL AND created_at < :cutoff
                """), {"cutoff": cutoff})
                rows = result.fetchall()

                deleted = 0
                for row in rows:
                    try:
                        p = Path(row.pdf_path)
                        if p.exists():
                            p.unlink()
                            deleted += 1
                    except Exception:
                        pass
                    await db.execute(text(
                        "UPDATE report_deliveries SET pdf_path = NULL, pdf_size_bytes = NULL WHERE id = :id"
                    ), {"id": row.id})

                if rows:
                    await db.commit()
                    logger.info("[PDFCleanup] Deleted %d old PDF(s)", deleted)
        except Exception as e:
            logger.error("[PDFCleanup] Error: %s", e)
        await asyncio.sleep(86400)  # 24 hours


def _render_report_email_html(
    company_name: str,
    report_name: str,
    period_start: date,
    period_end: date,
    primary_color: str = "#3b82f6",
) -> str:
    return (
        '<!DOCTYPE html><html><head><meta charset="UTF-8"></head>'
        '<body style="margin:0;padding:0;background:#f0f4f8;font-family:\'Segoe UI\',Arial,sans-serif;">'
        '<div style="max-width:520px;margin:40px auto;background:#fff;border-radius:12px;'
        'overflow:hidden;box-shadow:0 2px 16px rgba(0,0,0,0.08);">'
        '<div style="background:#1e293b;padding:24px 32px;text-align:center;">'
        f'<div style="color:#fff;font-size:22px;font-weight:700;">{company_name}</div>'
        '<div style="color:#94a3b8;font-size:13px;margin-top:4px;">Monitoring Report</div>'
        '</div>'
        f'<div style="background:{primary_color};padding:12px 32px;text-align:center;">'
        f'<span style="color:#fff;font-size:16px;font-weight:700;">{report_name}</span>'
        '</div>'
        '<div style="padding:28px 32px;">'
        '<p style="color:#334155;font-size:15px;margin:0 0 16px;">'
        'Your infrastructure report is attached as a PDF.</p>'
        '<table style="width:100%;border-collapse:collapse;font-size:14px;color:#334155;">'
        f'<tr><td style="padding:6px 0;font-weight:600;width:40%;">Period</td>'
        f'<td>{period_start.isoformat()} – {period_end.isoformat()}</td></tr>'
        '</table>'
        '</div>'
        '<div style="padding:16px 32px;background:#f8fafc;border-top:1px solid #e2e8f0;">'
        f'<p style="color:#94a3b8;font-size:12px;margin:0;">Generated by {company_name}</p>'
        '</div>'
        '</div></body></html>'
    )
